version: "3.3"

networks:
  qtumd_regtest_network:
volumes:
  qtumd_regtest_volume:

services:
  janus_regtest:
    image: qtum/janus:dev
    container_name: janus_regtest
    build: 
        context: ../../
        cache_from:
          - golang:1.14-alpine
    ports:
        - "23889:23889"
    environment: 
        - QTUM_RPC=http://qtum:testpasswd@qtum_regtest:3889
        - COMPOSE_PROJECT_NAME=regtest
    volumes:
        - ../standalone/myaccounts.txt:$GOPATH/github.com/qtumproject/janus/myaccounts.txt
        - ../../https:/https
        - ../../logs:/logs
    depends_on:
      - qtum_regtest
    command: --bind 0.0.0.0 --accounts $GOPATH/github.com/qtumproject/janus/myaccounts.txt --log-file /logs/janusLogs.txt --dev --https-key /https/key.pem --https-cert /https/cert.pem
    networks:
      - qtumd_regtest_network

  qtum_regtest:
    ports:
      - "3889:3889"
    image: qtum/qtum
    container_name: qtum_regtest
    command: qtumd -regtest -txindex -addrindex=1 -rpcbind=0.0.0.0:3889 -rpcallowip=0.0.0.0/0 -logevents -rpcuser=qtum -rpcpassword=testpasswd -deprecatedrpc=accounts -printtoconsole
    volumes:
      - qtumd_regtest_volume:/root/.qtum
    networks:
      - qtumd_regtest_network
